variables:
  buildConfiguration: 'Release'
  system.debug: 'true'

pool: default

resources:
  pipelines:

    - pipeline: mycircleciartifact
      type: pranpati.circleci.artifact
      endpoint: CircleCI
      project: github/PranaySPatil/circleci-demo-python-django
      version: 3

steps:
 
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'gci env:* | sort-object name'

- downloadArtifacts: mycircleciartifact
  artifacts:
    - name: circleci-artifact
      pattern: '**/**Author**'
