# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project to prod.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: '0b04962d-8e4c-4bf1-a246-22b870eb11a2'
    pipeline: '2982'
    buildVersionToDownload: 'specific'
    buildId: 532514
    artifactName: 'SpecialArtifact'
    specificBuildWithTriggering: true    
    downloadType: 'single'
    downloadPath: '$(System.ArtifactsDirectory)'
