variables:
  buildConfiguration: 'Release'
  system.debug: 'true'

pool: default

resources:
  pipelines:

    - pipeline: mycircleciartifact
      type: pranpati.circleci.artifact
      endpoint: CircleCI
      project: github/PranaySPatil/circleci-demo-python-django

    - pipeline: mygithubreleasesartifact
      type: ms-vscs-rm.vss-services-github-releases.github-releases-release-artifact-type
      endpoint: GitHubRelease
      definition: Lovakumar/TestApp
      version: 14249929

steps:
 
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'gci env:* | sort-object name'

- downloadArtifacts: mycircleciartifact
  artifacts:
    - name: circleci-artifact
      pattern: '**/**Author**'

- downloadArtifacts: mygithubreleasesartifact
  artifacts:
    - name: mygithubreleasesartifact
